# Server Setting
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    additional-tld-skip-patterns: "*.jar"
spring:
  mvc:
    pathmatch:
#     swagger IBM ISSUE :
#     Spring boot 2.6버전 이후에 spring.mvc.pathmatch.matching-strategy 값이 ant_apth_matcher에서
#     path_pattern_parser로 변경되면서 몇몇 라이브러리(swagger포함)에 오류가 발생하는 문제로 수정.
      matching-strategy: ant_path_matcher
#    jsp 페이지 있을때 추가
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
#  jpa 설정
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#  profiles:
#    active: dev-db
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: true
springdoc:
  version: v1.0.0
  packages-to-scan: indi.gradle.spring.study.apis.test
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
#   jwttoken 발급을위한 secret-key, 토큰 허용시간
security:
  jwt:
    token:
      secret-key: studydev111
      expire-length: 3600000  # milli seconds